# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lO4VS0z5LhLMR_dQoIXBWl64XGzwCnpM
"""

import pandas as pd

# Read in the two Excel sheets
sheet1 = pd.read_excel('excel_sheet1.xlsx')
sheet2 = pd.read_excel('excel_sheet2.xlsx')

# Create a dictionary of (project_id, employee_id, employee_name) tuples from sheet 1
id_dict = {(row['Project ID'], row['ID']): (row['ID'], row['Name']) for _, row in sheet1.iterrows()}

# Get a list of unique project IDs from both sheets
project_ids = sorted(set(sheet1['Project ID']).union(set(sheet2['Project ID'])))

# Assign new project IDs to projects in sheet 2 while keeping the same employee IDs for projects in sheet 1
unique_ids = list(range(1, len(sheet1['ID'].unique()) + 1))
for project_id in project_ids:
    if project_id in id_dict:
        # Use the same employee ID and name as in sheet 1
        employee_id, employee_name = id_dict[project_id]
    else:
        # Assign a new project ID to a unique employee in sheet 1
        employee_id, employee_name = None, None
        if project_id in sheet1['Project ID'].unique():
            employee_id = sheet1.loc[sheet1['Project ID'] == project_id, 'ID'].values[0]
            employee_name = sheet1.loc[sheet1['Project ID'] == project_id, 'Name'].values[0]
        elif unique_ids:
            employee_id, employee_name = unique_ids.pop(0), ''
        id_dict[project_id] = (employee_id, employee_name)
    # Update the ID and Name columns in sheet 2
    sheet2.loc[sheet2['Project ID'] == project_id, 'ID'] = employee_id
    sheet2.loc[sheet2['Project ID'] == project_id, 'Name'] = employee_name

# Print the updated sheet 2
print(sheet2)